apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/phu-maiminh-gmail-com/fish-api:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/phu-maiminh-gmail-com/fish-api:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: fish-api
        chartPath: charts/fish-api
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/phu-maiminh-gmail-com/fish-api"
          image.tag: "{{.TAG}}"
        